baseURL = "https://www.inkshare.in"
themesDir = "themes"
theme = "hugo-serif-theme"
languageCode = "en-us"
title = "InkShare - AI Powered Digital Pen & Disbound Stationery"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[params]
  google_analytics_id = "G-0SDV594WTB"
  google_tag_manager_id = ""
  favicon = "favicon-32x32.png"

  [params.homepage]
    show_contact_box = true
    show_services_button = true

  [params.logo]
    mobile = "images/logo/inkshare-1.png"
    mobile_height = "36px"
    desktop = "images/logo/inkshare-1.png"
    desktop_height = "36px"
    alt = "InkShare - Write, Share Anywhere"

  [params.fonts]
    google_fonts = 'https://fonts.googleapis.com/css2?family=Playfair+Display:wght@600&family=Source+Sans+Pro:wght@400;700&display=swap'
    heading = "Playfair Display"
    base = "Source Sans Pro"

  [params.colors]
    primary = "#ed725f"  # Orange
    black = "#2f2f41"
    white = "#ffffff"
    white_offset = "#f6f7ff"
    grey = "#5C5A5A"

  [params.seo]
    meta_twitter_site = "@inkshare"
    meta_twitter_creator = "@_InkShare"
    meta_og_image = "https://www.inkshare.in/images/inkshare_preview.png"
    meta_description = "InkShare offers AI-powered digital pens and disbound stationery, helping professionals capture, sync, and organize their thoughts effortlessly."

  [params.services]
    summary_truncate = 120 # Number charecters

  [params.team]
    summary_large_truncate = 120 # Number charecters

  [params.footer]
    copyright_text = 'InkShare @2024 <a class="zerostatic" href="https://www.inkshare.in">www.inkshare.in</a>'

[menu]
  [[menu.main]]
  name = "Products"
  url = "/products/"
  weight = 1

  [[menu.main]]
  name = "Team"
  url = "/team/"
  weight = 2

  [[menu.main]]
  name = "About"
  url = "/about/"
  weight = 3

  [[menu.main]]
  name = "Contact"
  url = "/contact/"
  weight = 4

  [[menu.footer]]
  name = "Home"
  url = "/"
  weight = 1

  [[menu.footer]]
  name = "Contact"
  url = "/contact/"
  weight = 2
